apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: flask
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: backend-image
          image: backend:latest  
          env:
            - name: SQLALCHEMY_DATABASE_URI
              value: postgres://koech:password@postgres-service:5432/mydatabase
            - name: SQLALCHEMY_TRACK_MODIFICATIONS
              value: "False"
          ports:
            - containerPort: 5000
